"""update fixed table!!

Revision ID: 50d213ec0fb0
Revises: 42d66006a1bd
Create Date: 2025-11-20 11:43:42.748153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50d213ec0fb0'
down_revision = '42d66006a1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixeds',
    sa.Column('fixed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=False),
    sa.Column('default_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('fixed_id')
    )
    op.create_table('fixed_histories',
    sa.Column('fixed_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixed_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_id'], ['fixeds.fixed_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('fixed_history_id')
    )
    op.drop_table('fixed_cost_histories')
    op.drop_table('fixed_costs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_costs',
    sa.Column('fixed_cost_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('billing_day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fixed_costs_ibfk_1'),
    sa.PrimaryKeyConstraint('fixed_cost_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fixed_cost_histories',
    sa.Column('history_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fixed_cost_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paid_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_cost_id'], ['fixed_costs.fixed_cost_id'], name=op.f('fixed_cost_histories_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fixed_cost_histories_ibfk_2')),
    sa.PrimaryKeyConstraint('history_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('fixed_histories')
    op.drop_table('fixeds')
    # ### end Alembic commands ###
