"""rename password to password_hash

Revision ID: ee5338986e6c
Revises: bbb51d39b0d5
Create Date: 2025-11-11 15:06:12.497239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee5338986e6c'
down_revision = 'bbb51d39b0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
